const $ = (s) => document.querySelector(s);
const views = ['dashboard','projects','tasks','runs','settings'];
const state = { projects: [], tasks: [], runs: [], selectedRun: null, streams: new Map() };

async function api(path, options = {}) { const res = await fetch(path, { headers: { 'content-type':'application/json', ...options.headers }, ...options }); const data = await res.json(); if (!res.ok) throw new Error(data.error?.message || 'Request failed'); return data; }
function esc(value=''){ return String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])); }
function setView(view){ views.forEach(v => $(`#${v}-view`).classList.toggle('hidden', v!==view)); document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); $('#page-title').textContent=view[0].toUpperCase()+view.slice(1); }
async function load(){ const [p,t,r] = await Promise.all([api('/api/projects'),api('/api/tasks'),api('/api/runs')]); state.projects=p.projects; state.tasks=t.tasks; state.runs=r.runs; renderAll(); }
function renderAll(){ renderDashboard(); renderProjects(); renderTasks(); renderRuns(); renderSettings(); }
function renderDashboard(){ const verified=state.runs.filter(r=>r.state==='verified').length; $('#dashboard-view').innerHTML=`<div class="grid"><div class="card"><span class="label">Projects</span><div class="metric">${state.projects.length}</div></div><div class="card"><span class="label">Tasks</span><div class="metric">${state.tasks.length}</div></div><div class="card"><span class="label">Runs</span><div class="metric">${state.runs.length}</div></div><div class="card"><span class="label">Verified</span><div class="metric">${verified}</div></div></div><div class="card panel"><div class="row"><div><h2>Launch a safe demo</h2><p class="muted">Use the local provider to exercise Planner → Builder → Reviewer → Verifier without an external AI key.</p></div><button class="primary" id="quick-demo">Create Demo Task</button></div></div><div class="card panel"><h2>Recent runs</h2>${runListHtml()}</div>`; $('#quick-demo').onclick=quickDemo; wireRunLinks(); }
function runListHtml(){ return state.runs.length ? `<div class="list">${state.runs.slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,8).map(r=>`<div class="item" data-run="${r.id}"><div class="row"><strong>${esc(r.summary||r.state)}</strong><span class="chip">${r.state}</span></div><span class="muted">${esc(r.id)} · ${esc(r.stage||'')}</span></div>`).join('')}</div>` : '<p class="muted">No runs yet.</p>'; }
function wireRunLinks(){ document.querySelectorAll('[data-run]').forEach(el=>el.onclick=()=>selectRun(el.dataset.run)); }
function renderProjects(){ $('#projects-view').innerHTML=`<div class="two"><div class="card"><h2>Register project</h2><div class="stack"><input class="field" id="project-name" placeholder="Project name"><input class="field" id="project-root" placeholder="Absolute local directory path"><button class="primary" id="add-project">Register</button></div></div><div class="card"><h2>Projects</h2><div class="list">${state.projects.map(p=>`<div class="item"><strong>${esc(p.name)}</strong><div class="muted">${esc(p.root)}</div><span class="chip">${esc(p.id)}</span></div>`).join('')||'<p class="muted">Register your first project.</p>'}</div></div></div>`; $('#add-project').onclick=async()=>{ try{ const p=await api('/api/projects',{method:'POST',body:JSON.stringify({name:$('#project-name').value,root:$('#project-root').value})}); state.projects.push(p.project); renderAll(); }catch(e){ alert(e.message); } }; }
function renderTasks(){ $('#tasks-view').innerHTML=`<div class="two"><div class="card"><h2>Create task</h2><div class="stack"><select id="task-project">${state.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select><input class="field" id="task-title" placeholder="Task title"><textarea id="task-prompt" rows="6" placeholder="Try: DEMO: create verified artifact"></textarea><button class="primary" id="add-task">Create task</button></div></div><div class="card"><h2>Task queue</h2><div class="list">${state.tasks.slice().reverse().map(t=>`<div class="item"><div class="row"><strong>${esc(t.title)}</strong><button class="primary" data-start="${t.id}">Run</button></div><div class="muted">${esc(t.prompt)}</div></div>`).join('')||'<p class="muted">No tasks yet.</p>'}</div></div></div>`; $('#add-task').onclick=async()=>{ try{const x=await api('/api/tasks',{method:'POST',body:JSON.stringify({projectId:$('#task-project').value,title:$('#task-title').value,prompt:$('#task-prompt').value})}); state.tasks.push(x.task); renderAll(); }catch(e){alert(e.message)} }; document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>startRun(b.dataset.start)); }
async function startRun(taskId){ try{ await api(`/api/tasks/${taskId}/run`,{method:'POST'}); setView('runs'); await refreshRuns(); }catch(e){alert(e.message)} }
async function refreshRuns(){ const x=await api('/api/runs'); state.runs=x.runs; renderDashboard(); renderRuns(); }
function renderRuns(){ const selected=state.selectedRun?state.runs.find(r=>r.id===state.selectedRun):null; $('#runs-view').innerHTML=`<div class="two"><div class="card"><h2>Run history</h2>${runListHtml()}</div><div class="card">${selected?runInspector(selected):'<h2>Select a run</h2><p class="muted">Live stages, evidence and rollback details appear here.</p>'}</div></div>`; wireRunLinks(); }
function runInspector(r){ const stages=['planner','builder','reviewer','fixer','verifier']; const currentIndex=stages.indexOf(r.stage||'planner'); return `<div class="row"><h2>Run inspector</h2><span class="chip">${esc(r.state)}</span></div><p class="muted">${esc(r.id)}</p><div class="stages">${stages.map((s,i)=>`<span class="stage ${i<=currentIndex?'done':''}">${s}</span>`).join('')}</div><h3>Evidence</h3><div class="list">${(r.evidence||[]).map(e=>`<div class="item"><div class="row"><strong>${esc(e.name)}</strong><span class="chip">${e.passed?'PASS':'FAIL'}</span></div><span class="muted">${esc(e.summary)}</span></div>`).join('')||'<p class="muted">None yet.</p>'}</div><h3>Changed files</h3><div class="code">${esc((r.changedFiles||[]).join('\n')||'No files')}</div>${r.error?`<div class="card"><strong>Error</strong><p class="muted">${esc(r.error)}</p></div>`:''}${r.checkpoint&&!r.rolledBackAt?`<button class="danger" id="rollback">Rollback checkpoint</button>`:''}${r.rolledBackAt?`<p class="muted">Rolled back at ${esc(r.rolledBackAt)}</p>`:''}`; }
async function selectRun(id){ state.selectedRun=id; const x=await api(`/api/runs/${id}`); state.runs=state.runs.some(r=>r.id===id)?state.runs.map(r=>r.id===id?x.run:r):[...state.runs,x.run]; renderRuns(); if(state.streams.has(id)) state.streams.get(id).close(); const es=new EventSource(`/api/runs/${id}/events`); state.streams.set(id,es); es.addEventListener('nexus',()=>refreshRuns().catch(()=>{})); es.addEventListener('error',()=>{}); }
$('#runs-view').addEventListener('click', async(e)=>{ if(e.target.id==='rollback' && state.selectedRun){ if(!confirm('Rollback this run?')) return; try{await api(`/api/runs/${state.selectedRun}/rollback`,{method:'POST'}); await selectRun(state.selectedRun);}catch(err){alert(err.message)} } });
async function quickDemo(){ const project=state.projects[0]; if(!project){setView('projects'); alert('Register a project first.'); return;} setView('tasks'); $('#task-project').value=project.id; $('#task-title').value='Verified demo'; $('#task-prompt').value='DEMO: create verified artifact'; $('#add-task').click(); }
function renderSettings(){ $('#settings-view').innerHTML='<div class="card"><h2>Runtime</h2><p class="muted">Provider: deterministic local provider</p><p class="muted">Server: local Node.js control center on port 4000</p><p class="muted">Model providers may be added through the provider interface. Providers never receive direct filesystem or process access.</p></div>'; }
async function boot(){ try{await api('/api/health'); $('#connection').textContent='Local runtime online'; await load(); }catch(e){ $('#connection').textContent='Runtime unavailable'; console.error(e); } }
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view)); $('#demo-btn').onclick=quickDemo; boot();
